

import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Richie rules",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <main className="flex p-5 h-lvh">this main
          <nav className="w-16 min-h-full">
            <div className="pr-5"></div>
          </nav>
          <section className="w-5/6 bg-white rounded-lg shadow-md">
            <div className="p-6"> {children}</div>
          </section>
        </main>
      </body>
    </html>
  );
}
